# Generated by Django 6.0.1 on 2026-02-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_address_order_city_order_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
